name: PLACEHOLDER

on:
  pull_request:
  push:

jobs:
  formats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: pre-commit
        run: pipx install pre-commit
      - run: pre-commit run --all-files --show-diff-on-failure

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: nox
        run: pipx install nox
      - run: nox -s tests
